# Generated by Django 5.0.2 on 2025-04-24 14:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chain", models.CharField(max_length=50, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_testnet", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "区块链",
                "verbose_name_plural": "区块链",
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=100)),
                ("decimals", models.IntegerField(default=18)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="CryptoAnalyst.chain",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TechnicalAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("rsi", models.FloatField(null=True)),
                ("macd_line", models.FloatField(null=True)),
                ("macd_signal", models.FloatField(null=True)),
                ("macd_histogram", models.FloatField(null=True)),
                ("bollinger_upper", models.FloatField(null=True)),
                ("bollinger_middle", models.FloatField(null=True)),
                ("bollinger_lower", models.FloatField(null=True)),
                ("bias", models.FloatField(null=True)),
                ("psy", models.FloatField(null=True)),
                ("dmi_plus", models.FloatField(null=True)),
                ("dmi_minus", models.FloatField(null=True)),
                ("dmi_adx", models.FloatField(null=True)),
                ("vwap", models.FloatField(null=True)),
                ("funding_rate", models.FloatField(null=True)),
                ("exchange_netflow", models.FloatField(null=True)),
                ("nupl", models.FloatField(null=True)),
                ("mayer_multiple", models.FloatField(null=True)),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technical_analysis",
                        to="CryptoAnalyst.token",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "get_latest_by": "timestamp",
            },
        ),
        migrations.CreateModel(
            name="MarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("price", models.FloatField()),
                ("volume", models.FloatField(null=True)),
                ("price_change_24h", models.FloatField(null=True)),
                ("price_change_percent_24h", models.FloatField(null=True)),
                ("high_24h", models.FloatField(null=True)),
                ("low_24h", models.FloatField(null=True)),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_data",
                        to="CryptoAnalyst.token",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "get_latest_by": "timestamp",
            },
        ),
        migrations.CreateModel(
            name="AnalysisReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("indicators_analysis", models.JSONField()),
                ("trend_analysis", models.JSONField()),
                ("trading_advice", models.JSONField()),
                ("risk_assessment", models.JSONField()),
                (
                    "technical_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_reports",
                        to="CryptoAnalyst.technicalanalysis",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_reports",
                        to="CryptoAnalyst.token",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "get_latest_by": "timestamp",
            },
        ),
    ]
