# Generated by Django 5.0.2 on 2025-04-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CryptoAnalyst", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenanalysisdata",
            name="bias",
            field=models.FloatField(blank=True, help_text="乖离率", null=True),
        ),
        migrations.AddField(
            model_name="tokenanalysisdata",
            name="bollinger_lower",
            field=models.FloatField(blank=True, help_text="布林带下轨", null=True),
        ),
        migrations.AddField(
            model_name="tokenanalysisdata",
            name="bollinger_middle",
            field=models.FloatField(blank=True, help_text="布林带中轨", null=True),
        ),
        migrations.AddField(
            model_name="tokenanalysisdata",
            name="bollinger_upper",
            field=models.FloatField(blank=True, help_text="布林带上轨", null=True),
        ),
        migrations.AddField(
            model_name="tokenanalysisdata",
            name="dmi_adx",
            field=models.FloatField(blank=True, help_text="DMI ADX", null=True),
        ),
        migrations.AddField(
            model_name="tokenanalysisdata",
            name="dmi_minus",
            field=models.FloatField(blank=True, help_text="DMI-DI", null=True),
        ),
        migrations.AddField(
            model_name="tokenanalysisdata",
            name="dmi_plus",
            field=models.FloatField(blank=True, help_text="DMI+DI", null=True),
        ),
        migrations.AddField(
            model_name="tokenanalysisdata",
            name="funding_rate",
            field=models.FloatField(blank=True, help_text="资金费率", null=True),
        ),
        migrations.AddField(
            model_name="tokenanalysisdata",
            name="macd_histogram",
            field=models.FloatField(blank=True, help_text="MACD柱状图", null=True),
        ),
        migrations.AddField(
            model_name="tokenanalysisdata",
            name="macd_line",
            field=models.FloatField(blank=True, help_text="MACD线", null=True),
        ),
        migrations.AddField(
            model_name="tokenanalysisdata",
            name="macd_signal",
            field=models.FloatField(blank=True, help_text="MACD信号线", null=True),
        ),
        migrations.AddField(
            model_name="tokenanalysisdata",
            name="psy",
            field=models.FloatField(blank=True, help_text="心理线", null=True),
        ),
        migrations.AddField(
            model_name="tokenanalysisdata",
            name="rsi",
            field=models.FloatField(blank=True, help_text="相对强弱指标", null=True),
        ),
        migrations.AddField(
            model_name="tokenanalysisdata",
            name="vwap",
            field=models.FloatField(
                blank=True, help_text="成交量加权平均价格", null=True
            ),
        ),
    ]
