# Generated by Django 5.0.2 on 2025-04-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CryptoAnalyst", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicalanalysis",
            name="bias_analysis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technicalanalysis",
            name="bias_support_trend",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="technicalanalysis",
            name="bollinger_analysis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technicalanalysis",
            name="bollinger_support_trend",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="technicalanalysis",
            name="dmi_analysis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technicalanalysis",
            name="dmi_support_trend",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="technicalanalysis",
            name="exchange_netflow_analysis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technicalanalysis",
            name="exchange_netflow_support_trend",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="technicalanalysis",
            name="funding_rate_analysis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technicalanalysis",
            name="funding_rate_support_trend",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="technicalanalysis",
            name="macd_analysis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technicalanalysis",
            name="macd_support_trend",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="technicalanalysis",
            name="mayer_multiple_analysis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technicalanalysis",
            name="mayer_multiple_support_trend",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="technicalanalysis",
            name="nupl_analysis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technicalanalysis",
            name="nupl_support_trend",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="technicalanalysis",
            name="psy_analysis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technicalanalysis",
            name="psy_support_trend",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="technicalanalysis",
            name="rsi_analysis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technicalanalysis",
            name="rsi_support_trend",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="technicalanalysis",
            name="vwap_analysis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technicalanalysis",
            name="vwap_support_trend",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
