# Generated by Django 5.0.2 on 2025-05-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CryptoAnalyst", "0002_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisreport",
            name="snapshot_price",
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name="PasswordResetToken",
        ),
    ]
