# Generated by Django 5.0.2 on 2025-04-24 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CryptoAnalyst", "0002_technicalanalysis_bias_analysis_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technicalanalysis",
            name="bias_analysis",
        ),
        migrations.RemoveField(
            model_name="technicalanalysis",
            name="bias_support_trend",
        ),
        migrations.RemoveField(
            model_name="technicalanalysis",
            name="bollinger_analysis",
        ),
        migrations.RemoveField(
            model_name="technicalanalysis",
            name="bollinger_support_trend",
        ),
        migrations.RemoveField(
            model_name="technicalanalysis",
            name="dmi_analysis",
        ),
        migrations.RemoveField(
            model_name="technicalanalysis",
            name="dmi_support_trend",
        ),
        migrations.RemoveField(
            model_name="technicalanalysis",
            name="exchange_netflow_analysis",
        ),
        migrations.RemoveField(
            model_name="technicalanalysis",
            name="exchange_netflow_support_trend",
        ),
        migrations.RemoveField(
            model_name="technicalanalysis",
            name="funding_rate_analysis",
        ),
        migrations.RemoveField(
            model_name="technicalanalysis",
            name="funding_rate_support_trend",
        ),
        migrations.RemoveField(
            model_name="technicalanalysis",
            name="macd_analysis",
        ),
        migrations.RemoveField(
            model_name="technicalanalysis",
            name="macd_support_trend",
        ),
        migrations.RemoveField(
            model_name="technicalanalysis",
            name="mayer_multiple_analysis",
        ),
        migrations.RemoveField(
            model_name="technicalanalysis",
            name="mayer_multiple_support_trend",
        ),
        migrations.RemoveField(
            model_name="technicalanalysis",
            name="nupl_analysis",
        ),
        migrations.RemoveField(
            model_name="technicalanalysis",
            name="nupl_support_trend",
        ),
        migrations.RemoveField(
            model_name="technicalanalysis",
            name="psy_analysis",
        ),
        migrations.RemoveField(
            model_name="technicalanalysis",
            name="psy_support_trend",
        ),
        migrations.RemoveField(
            model_name="technicalanalysis",
            name="rsi_analysis",
        ),
        migrations.RemoveField(
            model_name="technicalanalysis",
            name="rsi_support_trend",
        ),
        migrations.RemoveField(
            model_name="technicalanalysis",
            name="vwap_analysis",
        ),
        migrations.RemoveField(
            model_name="technicalanalysis",
            name="vwap_support_trend",
        ),
    ]
