# Generated by Django 5.0.2 on 2025-04-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CryptoAnalyst", "0003_remove_technicalanalysis_bias_analysis_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysisreport",
            name="risk_assessment",
        ),
        migrations.RemoveField(
            model_name="analysisreport",
            name="trading_advice",
        ),
        migrations.RemoveField(
            model_name="analysisreport",
            name="trend_analysis",
        ),
        migrations.AddField(
            model_name="analysisreport",
            name="entry_price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="analysisreport",
            name="risk_details",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="analysisreport",
            name="risk_level",
            field=models.CharField(default="中", max_length=10),
        ),
        migrations.AddField(
            model_name="analysisreport",
            name="risk_score",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="analysisreport",
            name="stop_loss",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="analysisreport",
            name="take_profit",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="analysisreport",
            name="trading_action",
            field=models.CharField(default="等待", max_length=20),
        ),
        migrations.AddField(
            model_name="analysisreport",
            name="trading_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="analysisreport",
            name="trend_down_probability",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="analysisreport",
            name="trend_sideways_probability",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="analysisreport",
            name="trend_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="analysisreport",
            name="trend_up_probability",
            field=models.IntegerField(default=0),
        ),
    ]
