# Generated by Django 5.0.2 on 2025-04-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CryptoAnalyst", "0007_invitationcode_user_invitation_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
