# Generated by Django 5.0.2 on 2025-04-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CryptoAnalyst", "0008_remove_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="", max_length=150, unique=True, verbose_name="用户名"
            ),
        ),
    ]
