# Generated by Django 5.0.2 on 2025-04-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CryptoAnalyst", "0009_alter_user_managers_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, unique=True, verbose_name="用户名"),
        ),
    ]
