# Generated by Django 5.0.2 on 2025-04-12 04:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chain", models.CharField(max_length=50, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("logo", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password_hash", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wallets.device"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=128)),
                ("private_key", models.CharField(max_length=256)),
                (
                    "chain",
                    models.CharField(
                        choices=[
                            ("ETH", "Ethereum"),
                            ("BSC", "BNB Chain"),
                            ("MATIC", "Polygon"),
                            ("AVAX", "Avalanche"),
                            ("BASE", "Base"),
                            ("OP", "Optimism"),
                            ("ARB", "Arbitrum"),
                            ("FTM", "Fantom"),
                            ("CRO", "Cronos"),
                            ("ZKSYNC", "zkSync Era"),
                            ("LINEA", "Linea"),
                            ("SCROLL", "Scroll"),
                            ("MANTA", "Manta"),
                            ("SOL", "Solana"),
                            ("KDA", "Kadena"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(default="", max_length=64)),
                ("is_watch_only", models.BooleanField(default=False)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="face/")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wallets.device"
                    ),
                ),
            ],
        ),
    ]
