# Generated by Django 5.0.2 on 2025-04-14 06:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chain", models.CharField(max_length=50, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="chain_logos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password_hash", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wallets.device"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("symbol", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("decimals", models.IntegerField(default=18)),
                ("logo_url", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "current_price_usd",
                    models.DecimalField(decimal_places=18, default=0, max_digits=30),
                ),
                (
                    "price_change_24h",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "market_cap_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=30),
                ),
                (
                    "volume_24h_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=30),
                ),
                (
                    "fully_diluted_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=30),
                ),
                (
                    "total_supply",
                    models.DecimalField(decimal_places=18, default=0, max_digits=40),
                ),
                (
                    "total_supply_formatted",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("standard", models.CharField(blank=True, max_length=20, null=True)),
                ("mint", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                ("twitter", models.URLField(blank=True, max_length=255, null=True)),
                ("telegram", models.URLField(blank=True, max_length=255, null=True)),
                ("discord", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "metadata_uri",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                ("is_master_edition", models.BooleanField(default=False)),
                ("is_mutable", models.BooleanField(default=True)),
                ("seller_fee_basis_points", models.IntegerField(default=0)),
                (
                    "update_authority",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("primary_sale_happened", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="wallets.chain",
                    ),
                ),
            ],
            options={
                "ordering": ["-current_price_usd"],
                "unique_together": {("chain", "address")},
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=128)),
                (
                    "private_key",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "chain",
                    models.CharField(
                        choices=[
                            ("ETH", "Ethereum"),
                            ("BSC", "BNB Chain"),
                            ("MATIC", "Polygon"),
                            ("AVAX", "Avalanche"),
                            ("BASE", "Base"),
                            ("OP", "Optimism"),
                            ("ARB", "Arbitrum"),
                            ("FTM", "Fantom"),
                            ("CRO", "Cronos"),
                            ("ZKSYNC", "zkSync Era"),
                            ("LINEA", "Linea"),
                            ("MANTA", "Manta"),
                            ("SOL", "Solana"),
                            ("KDA", "Kadena"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(default="", max_length=64)),
                ("is_watch_only", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="face/")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to="wallets.device",
                    ),
                ),
            ],
            options={
                "unique_together": {("device", "chain")},
            },
        ),
        migrations.CreateModel(
            name="WalletToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_address", models.CharField(max_length=255)),
                (
                    "balance",
                    models.DecimalField(decimal_places=18, default=0, max_digits=40),
                ),
                (
                    "balance_formatted",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "last_synced",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_tokens",
                        to="wallets.token",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_tokens",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-balance"],
                "unique_together": {("wallet", "token_address")},
            },
        ),
    ]
