# Generated by Django 5.0.2 on 2025-04-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettoken",
            name="chain",
            field=models.CharField(
                choices=[
                    ("ETH", "Ethereum"),
                    ("BSC", "BNB Chain"),
                    ("MATIC", "Polygon"),
                    ("AVAX", "Avalanche"),
                    ("BASE", "Base"),
                    ("OP", "Optimism"),
                    ("ARB", "Arbitrum"),
                    ("FTM", "Fantom"),
                    ("CRO", "Cronos"),
                    ("ZKSYNC", "zkSync Era"),
                    ("LINEA", "Linea"),
                    ("MANTA", "Manta"),
                    ("SOL", "Solana"),
                    ("KDA", "Kadena"),
                ],
                default="SOL",
                max_length=20,
            ),
        ),
    ]
