# Generated by Django 5.0.2 on 2025-04-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chain",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="chain_logos/"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="chain",
            field=models.CharField(
                choices=[
                    ("ETH", "Ethereum"),
                    ("BSC", "BNB Chain"),
                    ("MATIC", "Polygon"),
                    ("AVAX", "Avalanche"),
                    ("BASE", "Base"),
                    ("OP", "Optimism"),
                    ("ARB", "Arbitrum"),
                    ("FTM", "Fantom"),
                    ("CRO", "Cronos"),
                    ("ZKSYNC", "zkSync Era"),
                    ("LINEA", "Linea"),
                    ("MANTA", "Manta"),
                    ("SOL", "Solana"),
                    ("KDA", "Kadena"),
                ],
                max_length=32,
            ),
        ),
    ]
