# Generated by Django 5.0.2 on 2025-04-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="chain",
            field=models.CharField(
                choices=[
                    ("ETH", "Ethereum"),
                    ("BSC", "BNB Chain"),
                    ("MATIC", "Polygon"),
                    ("AVAX", "Avalanche"),
                    ("OP", "Optimism"),
                    ("ARB", "Arbitrum"),
                    ("SOL", "Solana"),
                    ("KDA", "Kadena"),
                ],
                max_length=32,
            ),
        ),
    ]
