# Generated by Django 5.0.2 on 2025-04-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0002_alter_wallet_chain"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="face/"),
        ),
    ]
