# Generated by Django 5.0.2 on 2025-04-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0002_alter_chain_logo_alter_wallet_chain"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
