# Generated by Django 5.0.2 on 2025-04-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0002_wallettoken_chain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="discord",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="logo_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="metadata_uri",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="telegram",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="twitter",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="website",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
