# Generated by Django 5.0.2 on 2025-04-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0003_alter_token_discord_alter_token_logo_url_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wallet",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="wallet",
            unique_together=set(),
        ),
    ]
