# Generated by Django 5.0.2 on 2025-04-13 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0004_tokenvisibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallets",
                to="wallets.device",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="private_key",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="wallet",
            unique_together={("device", "chain")},
        ),
    ]
