# Generated by Django 5.0.2 on 2025-04-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0004_alter_wallet_options_alter_wallet_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="fully_diluted_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=30, null=True
            ),
        ),
    ]
