# Generated by Django 5.0.2 on 2025-04-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0005_alter_token_fully_diluted_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="symbol",
            field=models.CharField(max_length=100),
        ),
    ]
