# Generated by Django 5.0.2 on 2025-04-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0006_alter_token_symbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="is_testnet",
            field=models.BooleanField(default=False),
        ),
    ]
