# Generated by Django 5.0.2 on 2025-04-15 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0007_chain_is_testnet"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="chain_obj",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallets",
                to="wallets.chain",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="chain",
            field=models.CharField(
                choices=[
                    ("ETH", "Ethereum"),
                    ("ETH_GOERLI", "Ethereum Goerli"),
                    ("ETH_SEPOLIA", "Ethereum Sepolia"),
                    ("BSC", "BNB Chain"),
                    ("BSC_TESTNET", "BNB Chain Testnet"),
                    ("MATIC", "Polygon"),
                    ("MATIC_MUMBAI", "Polygon Mumbai"),
                    ("AVAX", "Avalanche"),
                    ("AVAX_FUJI", "Avalanche Fuji"),
                    ("BASE", "Base"),
                    ("BASE_SEPOLIA", "Base Sepolia"),
                    ("OP", "Optimism"),
                    ("OP_GOERLI", "Optimism Goerli"),
                    ("ARB", "Arbitrum"),
                    ("ARB_GOERLI", "Arbitrum Goerli"),
                    ("FTM", "Fantom"),
                    ("FTM_TESTNET", "Fantom Testnet"),
                    ("CRO", "Cronos"),
                    ("CRO_TESTNET", "Cronos Testnet"),
                    ("ZKSYNC", "zkSync Era"),
                    ("ZKSYNC_TESTNET", "zkSync Era Testnet"),
                    ("LINEA", "Linea"),
                    ("LINEA_GOERLI", "Linea Goerli"),
                    ("MANTA", "Manta"),
                    ("MANTA_TESTNET", "Manta Pacific Testnet"),
                    ("SOL", "Solana"),
                    ("SOL_DEVNET", "Solana Devnet"),
                    ("SOL_TESTNET", "Solana Testnet"),
                    ("KDA", "Kadena"),
                    ("KDA_TESTNET", "Kadena Testnet"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="wallettoken",
            name="chain",
            field=models.CharField(
                choices=[
                    ("ETH", "Ethereum"),
                    ("ETH_GOERLI", "Ethereum Goerli"),
                    ("ETH_SEPOLIA", "Ethereum Sepolia"),
                    ("BSC", "BNB Chain"),
                    ("BSC_TESTNET", "BNB Chain Testnet"),
                    ("MATIC", "Polygon"),
                    ("MATIC_MUMBAI", "Polygon Mumbai"),
                    ("AVAX", "Avalanche"),
                    ("AVAX_FUJI", "Avalanche Fuji"),
                    ("BASE", "Base"),
                    ("BASE_SEPOLIA", "Base Sepolia"),
                    ("OP", "Optimism"),
                    ("OP_GOERLI", "Optimism Goerli"),
                    ("ARB", "Arbitrum"),
                    ("ARB_GOERLI", "Arbitrum Goerli"),
                    ("FTM", "Fantom"),
                    ("FTM_TESTNET", "Fantom Testnet"),
                    ("CRO", "Cronos"),
                    ("CRO_TESTNET", "Cronos Testnet"),
                    ("ZKSYNC", "zkSync Era"),
                    ("ZKSYNC_TESTNET", "zkSync Era Testnet"),
                    ("LINEA", "Linea"),
                    ("LINEA_GOERLI", "Linea Goerli"),
                    ("MANTA", "Manta"),
                    ("MANTA_TESTNET", "Manta Pacific Testnet"),
                    ("SOL", "Solana"),
                    ("SOL_DEVNET", "Solana Devnet"),
                    ("SOL_TESTNET", "Solana Testnet"),
                    ("KDA", "Kadena"),
                    ("KDA_TESTNET", "Kadena Testnet"),
                ],
                default="SOL",
                max_length=20,
            ),
        ),
    ]
