# Generated by Django 5.0.2 on 2025-04-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0002_fill_chain_obj"),
        ("wallets", "0008_wallet_chain_obj_alter_wallet_chain_and_more"),
    ]

    operations = []
