# Generated by Django 5.0.2 on 2025-04-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0009_merge_20250415_1225"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallettoken",
            name="chain",
        ),
    ]
