# Generated by Django 5.0.2 on 2025-04-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0010_remove_wallettoken_chain"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="kadena_chain_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
